- name: Gather git information
  import_tasks: git-info.yml

- name: Login to Docker Hub
  command: docker login -u {{ docker_username }} -p {{ docker_password }}
  vars:
    docker_username: "{{ lookup('aws_ssm', '/docker-hub/credentials/username', region='ap-southeast-2') }}"
    docker_password: "{{ lookup('aws_ssm', '/docker-hub/credentials/password', region='ap-southeast-2') }}"

- name: Publish Docker image
  shell: |
    docker tag video-downloader-{{ app_name }}:{{ git_branch }}-{{ git_commit }} ruchira088/video-downloader-{{ app_name }}:{{ git_branch }}-{{ git_commit }} && \
    docker push ruchira088/video-downloader-{{ app_name }}:{{ git_branch }}-{{ git_commit }}