apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migration-data-config-map
  namespace: "{{ k8s_namespace }}"
data:
{% for key, value in db_migration.config_values.items() %}
  "{{ key }}": "{{ value }}"
{% endfor %}
