apiVersion: v1
kind: Secret
metadata:
  name: db-migration-secrets
  namespace: "{{ k8s_namespace }}"
type: Opaque
stringData:
{% for key, value in db_migration.secrets.items() %}
  "{{ key }}": "{{ value }}"
{% endfor %}