apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: "{{ k8s_namespace }}"
type: Opaque
stringData:
{% for key, value in api.secrets.items() %}
  "{{ key }}": "{{ value }}"
{% endfor %}